import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/sideBar";
import NavigationBar from "./components/navigationBar";
import Footer from "./components/footerBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <NavigationBar />
        <div className="flex h-fit">
          <SideBar />
          
        <div className="flex-1 p-4">{children}</div>
        
        </div>
        <Footer />
      </body>
    </html>
  )
}
