name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  pull_and_run:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull rijanacharya100/bookfrontend:latest
      - name: Delete Old docker container
        run: sudo docker rm -f bookfrontend-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name bookfrontend-container rijanacharya100/bookfrontend